Azure/terraform-azurerm-caf-enterprise-scale

resources.policy_set_definitions.tf
Added missing fix for Policy Set Definitions bug
=> Fix for Policy Set Definitions bug

README.md, SECURITY.md, modules/terraform-azurerm-caf-enterprise-scale-archetypes/locals.role_definitions.tf, resources.role_definitions.tf
Minor bugfixes for the following:
- Ensure Role Definition name is correctly set when creating at scope other than root.
- Update README with additional information.
- Fix linting errors in markdown files.
=> Minor bugfixes

README.md, modules/terraform-azurerm-caf-enterprise-scale-archetypes/lib/archetype_definition_default_empty.json, modules/terraform-azurerm-caf-enterprise-scale-archetypes/locals.policy_assignments.tf, modules/terraform-azurerm-caf-enterprise-scale-archetypes/locals.role_assignments.tf
This PR contains the following changes:
- Updates to documentation in README
- Add "default_empty" archetype definition to built-in library
- Fix to ensure unique Role Assignment ID
- Add support for defining Policy Assignment parameters in archetype definitions
=> Update for release 0.0.7-preview

tests/pipelines/tests-e2e.yml, tests/pipelines/tests-unit.yml
Minor increment to Terraform and provider versions.
=> Increment matrix versions

README.md
Update to README.md for v0.1.1 release
=> Update docs for v0.1.1 release

variables.tf
=> Perform input validation on all custom landing zone keys

.github/scripts/EnterpriseScaleLibraryTools/EnterpriseScaleLibraryTools.psm1, .gitignore, README.md
This PR prepares the repository for the v0.1.2 release.
=> Updates for v0.1.2 release

locals.policy_assignments.tf, locals.tf, variables.tf
- Add role configuration override for Policy Assignment with Managed Identity
=> Role configuration override for Policy Assignments 

README.md
This PR udpates the readme for release v0.3.0
=> Update for release v0.3.0

locals.management_groups.tf, locals.policy_assignments.tf, tests/deployment/lib/archetype_definitions/archetype_definition_customer_secure.json, tests/deployment/main.tf, variables.tf
This PR fixes issue #89 `The given value is not suitable for child module variable "archetype_config_overrides"`
=> Hotfix 89 - The given value is not suitable for child module variable "archetype_config_overrides"

README.md, docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Default-Configuration.md, docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md, docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
This PR updates the docs in preparation for release `v0.3.1`
=> Update docs for release v0.3.1

docs/wiki/[User-Guide]-Getting-Started.md
Update version on Getting Started page to 0.3.1
=> Update version on Getting Started page to 0.3.1

README.md, docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Default-Configuration.md, docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md, docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md, docs/wiki/[User-Guide]-Getting-Started.md, tests/scripts/azp-strategy.ps1
This PR updates the docs in preparation for release `v0.3.2`
=> Update for release v0.3.2

modules/connectivity/locals.tf
1. Update boolean logic controlling deployment of `azurerm_private_dns_zone_virtual_network_link` resources (fixes #204)
2. Added parameter configuration in `connectivity` module to correctly configure `Enable-DDoS-VNET` Policy Assignment at `landing-zones` scope (fixes #216)
none
=> Bug fixes aligned to logged issues

.github/scripts/EnterpriseScaleLibraryTools/EnterpriseScaleLibraryTools.psm1, README.md, SECURITY.md, docs/wiki/Home.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources.md, docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Default-Configuration.md, docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Identity-Resources.md, docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Management-Resources.md, docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md, docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md, docs/wiki/[Examples]-Override-Module-Role-Assignments.md, docs/wiki/[User-Guide]-Connectivity-Resources.md, docs/wiki/[User-Guide]-Core-Resources.md, docs/wiki/[User-Guide]-Getting-Started.md, docs/wiki/[User-Guide]-Identity-Resources.md, docs/wiki/[User-Guide]-Management-Resources.md, docs/wiki/[User-Guide]-Module-Permissions.md, docs/wiki/[User-Guide]-Module-Variables.md, docs/wiki/[User-Guide]-Provider-Configuration.md, docs/wiki/[User-Guide]-Upgrade-from-v0.1.2-to-v0.2.0.md, docs/wiki/[User-Guide]-Upgrade-from-v0.3.3-to-v0.4.0.md, docs/wiki/[User-Guide]-Upgrade-from-v0.4.0-to-v1.0.0.md, docs/wiki/[Variables]-default_tags.md, docs/wiki/[Variables]-disable_base_module_tags.md, locals.tf
Update docs ready for release `v1.1.0`
1. Version updates in documentation
2. Version update in `base_module_tags` local variable
2. Update `customise` (`en-gb`) to `customize` (`en-us`)
3. Remove regionalization from Microsoft Docs links
None
n/a
=> Update ready for release `v1.1.0`

README.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources.md, docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Default-Configuration.md, docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Identity-Resources.md, docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Management-Resources.md, docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md, docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md, docs/wiki/[Examples]-Override-Module-Role-Assignments.md, docs/wiki/[User-Guide]-Getting-Started.md, docs/wiki/[User-Guide]-Provider-Configuration.md, locals.tf
Prepare `main` for the `v1.1.1` release.
1. Update base tags applied by the module to reflect the latest release
2. Update examples in Wiki
3. Add release notes to readme
none
n/a
=> Update ready for release `v1.1.1`

README.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources.md, docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Default-Configuration.md, docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Identity-Resources.md, docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Management-Resources.md, docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md, docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md, docs/wiki/[Examples]-Override-Module-Role-Assignments.md, docs/wiki/[User-Guide]-Getting-Started.md, docs/wiki/[User-Guide]-Provider-Configuration.md, locals.tf
This PR prepares `main` for the next release `v1.1.2`
1. Update the module version within the following:
1. Base module tags > `deployedBy` value
2. Wiki documentation
3. Readme
*none*
n/a (documentation update only)
=> Updates for release `v1.1.2`

outputs.tf, tests/modules/test_002_add_custom_core/planned_values.json, tests/modules/test_003_add_mgmt_conn/planned_values.json
This PR adds resource outputs for the VWAN resources
1. Fixes #305
none
=> Add resource outputs for VWAN

docs/wiki/[Variables]-configure_management_resources.md
=> Fix broken link in #329

resources.connectivity.tf
Fix incorrect object lookup
1. fixes #370
=> Fix incorrect object lookup

locals.tf
=> Remove module version from base_module_tags/deployedBy

docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
This PR fixes an invalid example for the Wiki page: [\[Examples\] Deploy Management Resources With Custom Settings](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Management-Resources-With-Custom-Settings)
1. Update Wiki page: [\[Examples\] Deploy Management Resources With Custom Settings](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/wiki/%5BExamples%5D-Deploy-Management-Resources-With-Custom-Settings)
n/a
Please compare change against:
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/blob/ac4dbc11c748be9b753291144033be7d663a17d0/variables.tf#L126-L139
=> Fix `configure_management_resources` value

modules/management/locals.tf
<h2 id=overviewsummary>Overview/Summary </h2>
<p>Replace this with a brief description of what this Pull Request fixes, changes, etc. </p>
<h2 id=thisprfixesaddschangesremoves>This PR fixes/adds/changes/removes </h2>
<ol>
<li>Fixes #449 </li>
<li>Contributes towards #227 </li>
</ol>
<h3 id=breakingchanges>Breaking Changes </h3>
<ol>
<li>For customers deploying Management resources to <code>East US</code> or <code>East US 2</code> regions, Terraform will want to destroy / create the automation account to move it to the correct location. </li>
</ol>
<blockquote>
<p>Customers not using <code>Update management</code> and who don't want to redeploy the automation account must add the following code to their module configuration: </p>
</blockquote>
<pre><code class="hcl language-hcl">  # within …
=> Update automation account region mapping

.github/workflows/wiki-sync.yml
<h2 id=overviewsummary>Overview/Summary </h2>
<p>This PR update the GitHub Action <code>Docs/Wiki Sync</code> to check for changes before trying to commit and push to the Wiki repository. </p>
<h2 id=thisprfixesaddschangesremoves>This PR fixes/adds/changes/removes </h2>
<ol>
<li>This PR prevents the following error from occurring: </li>
</ol>
<p><img src="https://user-images.githubusercontent.com/12268562/189948748-02aadbe5-1de2-4460-a3b7-2e4486f45930.png" alt="Image showing wiki sync error"> </p>
<h3 id=breakingchanges>Breaking Changes </h3>
<p>none </p>
<h2 id=testingevidence>Testing Evidence </h2>
<p>Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate). </p>
<p>Two concurrent runs: </p>
<p><img …
=> Update `Docs/Wiki Sync` to check for changes

README.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources.md, docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Default-Configuration.md, docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Identity-Resources.md, docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Management-Resources.md, docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md, docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources.md, docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md, docs/wiki/[Examples]-Override-Module-Role-Assignments.md, docs/wiki/[User-Guide]-Getting-Started.md, docs/wiki/[User-Guide]-Module-Releases.md, docs/wiki/[User-Guide]-Provider-Configuration.md, locals.version.tf
<h2 id=overviewsummary>Overview/Summary </h2>
<p>This PR includes documentation updates in preparation for release <code>v2.4.0</code> </p>
<h2 id=thisprfixesaddschangesremoves>This PR fixes/adds/changes/removes </h2>
<p>n/a </p>
<h3 id=breakingchanges>Breaking Changes </h3>
<p>n/a </p>
<h2 id=testingevidence>Testing Evidence </h2>
<p>Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if appropriate). </p>
<h2 id=aspartofthispullrequestihave>As part of this Pull Request I have </h2>
<ul>
<li>[x] Checked for duplicate <a href="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls">Pull Requests</a> </li>
<li>[x] Associated it with relevant <a …
=> Prepare for release `v2.4.0`

README.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources.md, docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Default-Configuration.md, docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Identity-Resources.md, docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Management-Resources.md, docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md, docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources.md, docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md, docs/wiki/[Examples]-Override-Module-Role-Assignments.md, docs/wiki/[User-Guide]-Getting-Started.md, docs/wiki/[User-Guide]-Module-Releases.md, docs/wiki/[User-Guide]-Provider-Configuration.md, locals.version.tf
Updates the module ready for release `v2.4.1`
n/a
n/a
n/a
=> Update ready for release `v2.4.1`

.github/workflows/gh-ado-sync.yml
Fix GH to ADO Sync Bugs. Convert to 1 way sync (GH to ADO only)
1. Fix GH to ADO Sync Bugs. Convert to 1 way sync (GH to ADO only)
None
Working in ALZ-Bicep repo and ADO - https://github.com/Azure/ALZ-Bicep/actions/workflows/gh-ado-sync.yml
=> Fix GH to ADO Sync Bugs

RELEASE.md, docs/wiki/Frequently-Asked-Questions.md
This PR updates the FAQ page to add responses for common questions
1. Close #378 
n/a
n/a
=> Update FAQ page

README.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Connectivity-Resources.md, docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Default-Configuration.md, docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md, docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Identity-Resources.md, docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Management-Resources.md, docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md, docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources-With-Custom-Settings.md, docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources.md, docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-orchestration.md, docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-remote-state.md, docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md, docs/wiki/[Examples]-Override-Module-Role-Assignments.md, docs/wiki/[User-Guide]-Getting-Started.md, docs/wiki/[User-Guide]-Module-upgrade-guidance.md, docs/wiki/[User-Guide]-Provider-Configuration.md, examples/400-multi-with-orchestration/modules/connectivity/main.tf, examples/400-multi-with-orchestration/modules/core/main.tf, examples/400-multi-with-orchestration/modules/management/main.tf, examples/400-multi-with-remote-state/connectivity/main.tf, examples/400-multi-with-remote-state/core/main.tf, examples/400-multi-with-remote-state/management/main.tf, locals.version.tf
This PR updates the module in preparation for release `v3.1.0`, including updates to examples and other references relating to the current release.
n/a
n/a
n/a
=> Update ready for release `v3.1.0`

.github/workflows/gh-ado-sync.yml
This PR includes an update to the concurrency group logic for ADO-sync action to set correct value using issue or PR ID value
n/a
n/a
Needs merging to test
=> Update concurrency group logic

README.md, _README_footer.md, _README_header.md
=> fix: Broken links in Terraform Registry in release `v3.2.0` #637

.github/workflows/update-policy.yml
Fix workflows that create PRs
1. Fix workflows that create PRs
None
Working in `ALZ-Bicep` and `ALZ-Monitor` repos
=> Fix workflows that create PRs

.github/scripts/Invoke-LibraryUpdatePolicyAssignmentArchetypes.ps1, .github/scripts/Invoke-LibraryUpdatePolicyAssignments.ps1, .github/workflows/update-policy.yml
This fixes a few bugs with the automated policy refresh code.
None
None
See successful run: https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/actions/runs/4884394033
=> Bug fix update policy action

README.md, locals.version.tf, modules/archetypes/lib/archetype_definitions/archetype_definition_es_platform.tmpl.json, modules/management/locals.tf, tests/modules/test_001_baseline/baseline_values.json, tests/modules/test_002_add_custom_core/baseline_values.json, tests/modules/test_003_add_mgmt_conn/baseline_values.json, variables.tf
1. fixes #713
2. fixes #717
3. fixes #700
=> fix: bugs in v4

.github/scripts/Invoke-LibraryUpdatePolicyAssignmentArchetypes.ps1
Fixes archetype sync from upstream
1. *Replace me*
2. *Replace me*
3. *Replace me*
1. *Replace me*
2. *Replace me*
=> fix: archetypesync

docs/wiki/[Examples]-Deploy-ZT-Network.md, docs/wiki/_Sidebar.md
As part of adding Zero Trust guidance to the Landing Zone reference implementation, this PR adds an article describing what variables to update in order to deploy with Zero Trust principles for networking.
1. Adds an article for "Deploying with Zero Trust Networking Principles" to the wiki
2. Updates the wiki to include this article as a 300 level item.
1.None.
No code change.
=> Deploy with Zero Trust Networking Principles Guide

docs/wiki/[Examples]-Deploy-ZT-Network.md
=> fix: wiki broken link

modules/connectivity/locals.tf
=> Fix: DNS Proxy Removal on FW whilst Upgrading 

README.md, _README_header.md
Adds to the Readme a link to the Upgrade guide from v4.2.0 to v5.0.0
1. adds link to the Upgrade guide from v4.2.0 to v5.0.0
only ReadME Update
=> add link to Upgrade guide from v4.2.0 to v5.0.0

.github/workflows/update-policy.yml
Adds an option to run the sync on a different branch of the enterprise scale repo. Useful for testing!
N/A
N/A
=> Add remote branch option

.github/workflows/scorecard.yml, README.md, _README_header.md
Add OpenSFF scoredcard and badge
N/A
N/A
N/A
=> Add OpenSFF Scorecard

docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
management configuration changed with v6, but documentation is not showing this, which might be confusing.
no changes to code
none
=> feat: add new management config to docu

tests/scripts/azp-strategy.ps1
Prevent use of AzureRM v4.0
1. *Replace me*
2. *Replace me*
=> test: pin max azurerm to 3.116.0

modules/connectivity/locals.tf
#1106
Updated spoke_virtual_networks_for_dns to include the secure virtual network ids
1. *Replace me*
2. *Replace me*
3. *Replace me*
1. *Replace me*
2. *Replace me*
=> Updated spoke_virtual_networks_for_dns to include the secure virtual network ids

README.md, _README_header.md, docs/wiki/_Header.md, modules/archetypes/README.md, modules/archetypes/_README_header.md, modules/connectivity/README.md, modules/connectivity/_README_header.md, modules/identity/README.md, modules/management/README.md, modules/management/_README_header.md, modules/role_assignments_for_policy/README.md, modules/role_assignments_for_policy/_README_header.md
Adds doc notice
** do not merge until w/c 20 January 2025 **
=> docs: add notice
