- data.subscription.tf
- modules/terraform-azurerm-enterprise-scale-archetypes/lib/archetype_definition_es_root.tmpl.json
- modules/terraform-azurerm-enterprise-scale-archetypes/lib/role_definition_es_network_contributor.json
- modules/terraform-azurerm-enterprise-scale-archetypes/locals.archetype_definitions.tf
- modules/terraform-azurerm-enterprise-scale-archetypes/locals.role_definitions.tf
- modules/terraform-azurerm-enterprise-scale-archetypes/locals.tf
- modules/terraform-azurerm-enterprise-scale-archetypes/variables.tf
- resources.role_definitions.tf
- variables.tf
This PR introduces a couple of changes.
1. The vairable `es_archetype_library_path` is now optional, allowing the module to be run with only specifying an input value for `es_root_parent_id`
2. Role Definitions are now created with a predicatable UUID generated from the template `name` value and the scope of the deployment, using the `uuidv5()` function. This is a breaking change as the creation of a new UUID will force recreation of existing Role Definitions, however this was deemed necessary to allow multiple Role Definition deployments from a single template, and the ability to deploy the module multiple times in a single Tenant.
> Role Definition Update

- README.md
- locals.management_groups.tf
When using the sample code in the readme, the parameter for subscription mapping would throw an error for not being required. Looked into the module and found the variable was incorrect, was `es_subscription_ids_map` and needed to be `subscription_id_overrides` as the map is a local and not a variable.
> Fixed instructions for subscription mapping

- resources.policy_assignments.tf
When you are deploying custom management with policy assignments, the graph will start assignments at the same time as management groups. Adding dependency to make sure MG gets created first.
> Adding dependencies on MG before policies assignment

- terraform.tf
Adds an internal `required_providers` configuration block to ensure the module is deployed using at least the minimum required provider versions, as per:
> If you are writing a shared Terraform module, constrain only the minimum required provider version using a `>=` constraint.
>This should specify the minimum version containing the features your module relies on, and thus allow a user of your module to potentially select a newer provider version if other features are needed by other parts of their overall configuration.
https://www.terraform.io/docs/language/modules/develop/providers.html#provider-version-constraints-in-modules
> Adds required_providers configuration block

- .github/scripts/EnterpriseScaleLibraryTools/EnterpriseScaleLibraryTools.psm1
- locals.policy_assignments.tf
- modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_asc_monitoring.tmpl.json
- modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deny_publicendpoints.tmpl.json
- modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_diag_loganalytics.tmpl.json
- modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_deploy_sql_security.tmpl.json
- modules/archetypes/lib/policy_set_definitions/policy_set_definition_es_enforce_encrypttransit.tmpl.json
- modules/archetypes/locals.policy_definitions.tf
- modules/archetypes/locals.policy_set_definitions.tf
This PR includes the following udpates and fixes:
- Updates the library templates to use `root_scope_resource_id` for policies deployed by this module
- Fix to remove incorrect Managed Identity from `Deploy-ASC-Monitoring` policy
- Fix to address missing Role Assignments for Policy Assignments using internal Policy Set Definitions
- Improve logic when processing Role Assignments for Policy Assignments with Managed Identities
- Initial work towards #51 where duplicate Policy Assignments at different scopes cause a duplicate key error
- Fix a bug where changing the `archetype_id` for an existing Management Group fails during the `plan` stage
> Patch Policy Issues

- modules/archetypes/locals.archetype_definitions.tf
This PR creates the logic used to add or remove additional configuration settings to an existing [built-in] or custom archetype definition without having to create a complete copy.
> Add or remove configuration settings from an existing [built-in] or custom archetype definition.

- modules/management/locals.tf
Following the update to Azure/Enterprise-Scale [PR#544](https://github.com/Azure/Enterprise-Scale/pull/544), this update is intended to maintain consistency on the Automation Account deployed as part of the Management landing zone resources.
> Update Automation Account naming logic

- locals.policy_assignments.tf
Add hotfix for github issue 48, to update the map of roles for Policy Definitions
> issue 48 hotfix

- modules/management/locals.tf
- modules/management/outputs.tf
- modules/management/variables.tf
This PR introduces a change to the logic used to set the Log Analytics workspace setting for `retention_in_days` to fix issue #99 
> **NOTE:** This is not a breaking change, but will result in an update to customer environments where this value has been modified in code but incorrectly applied in Azure,
> Update `retention_in_days` config to fix #99

- locals.management_groups.tf
- locals.tf
- main.tf
- modules/archetypes/lib/archetype_definitions/archetype_definition_es_identity.tmpl.json
- modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_public_ip.tmpl.json
- modules/identity/locals.tf
- modules/identity/main.tf
- modules/identity/outputs.tf
- modules/identity/variables.tf
- modules/management/variables.tf
- variables.tf
This PR adds the following features:
- Add the following new `Policy Assignments` at the `Identity` landing zones scope:
- "Deny-Public-IP"
- "Deny-RDP-From-Internet"
- "Deny-Subnet-Without-Nsg"
- "Deploy-VM-Backup"
- Integration with a new `Identity` child module, providing managed settings for both `parameters` and `enforcement_mode` on these `Policy Assignments`.
- Added the following new input `variables` to the module to enable configuration of the new `Identity` child module:
- `deploy_identity_resources`
- `configure_identity_resources`
> No breaking changes are included in this PR, but new resources will be created by the module
> Add "Identity" module

- locals.management_groups.tf
- modules/management/locals.tf
- tests/deployment/locals.core.tf
- tests/deployment/locals.management.tf
- tests/deployment/main.tf
- tests/deployment/variables.tf
- tests/scripts/tf-plan.sh
This PR introduces the following updates:
- The `deploy_management_resources` input variable is now decoupled from the logic used to control policy configuration in the `management` child module, allowing the `management resources` to be implemented independently from `core resources` without impacting the expected configuration specified by the `configure_management_resources` input variable.
- Test scenarios added for a custom `configure_management_resources` input variable to allow unit tests to be written to validate this functionality.
- The `connectivity_id_management` input variable now places the provided Subscription (by ID) into the `Connectivity` Management Group.
- The `identity_id_management` input variable now places the provided Subscription (by ID) into the `Identity` …
> Improvements to management logic

- .github/workflows/code-review.yml
- .gitignore
- README.md
- docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
- docs/wiki/[Examples]-Deploy-Default-Configuration.md
- docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
- docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
- docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
- docs/wiki/[User-Guide]-Getting-Started.md
- resources.management.tf
- tests/scripts/azp-spn-generator.sh
This PR introduces the following non-breaking changes:
- Update `github/super-linter` to use latest version
- Add `github/super-linter` output files to `.gitignore`
- Add explicit dependency between `azurerm_log_analytics_solution.enterprise_scale` and `azurerm_automation_account.enterprise_scale` to fix #109
- Remove tags from `azurerm_log_analytics_linked_service.enterprise_scale` to fix #121
- Fix workflow bug for SPN Generator when multiple Subscriptions are available
- Update docs for `v0.3.3` release
> Patch bugs for release v0.3.3

- tests/scripts/tf-prepare.sh
- **New features**:
- Test framework - replace `rm` with `shred` to securely delete private key file
> Replace `rm` with `shred`

- README.md
- tests/scripts/azp-spn-generator.sh
This PR is to address two issues:
1. Images on the default `README.md` do not render in Terraform Registry due to using relative path
2. The `azp-spn-generator.sh` script fails with error `ERROR: The specified vault: cae-estf-devops-kv already exists` since [PR #18520](https://github.com/Azure/azure-cli/pull/18520/) in the AZ CLI which breaks idempotency on this resource.
1. Update relative paths to absolute for images in `README.md`
2. Add logic to handle idempotency issue for `az keyvault create` command in `azp-spn-generator.sh` script, replacing error with logic to skip resource creation
*none*
Unable to provide evidence for link updates until published to registry.
The following is from a test run of the updated `azp-spn-generator.sh` script:
> Fix images in README.md and azp-spn-generator.sh error

- docs/wiki/[User-Guide]-Provider-Configuration.md
Fix Provider Declaration in provider config wiki page
1. Fix Provider Declaration in provider config wiki page
None
N/A
> Fix Provider Declaration

- docs/wiki/[Examples]-Deploy-Management-Resources.md
Fixes #218 - incorrect link on Deploy Management Resources wiki page
n/a
> fix incorrect wiki link

- tests/scripts/azp-strategy.ps1
Improves visibility of pipeline operations when generated a matrix strategy
1. Adds Subscription ID to output to improve debugging
n/a
> Add Subscription ID to output to improve debugging

- terraform.tf
Adds `required_version` to the module to [specify a required Terraform version](https://www.terraform.io/docs/language/settings/index.html#specifying-a-required-terraform-version) for the module.
1. Fixes #229 
none
Unable to evidence that this prevents previous versions from working due to https://github.com/hashicorp/terraform/issues/30105
Configuration is well known setting though.
> Add `required_version` for Terraform

- modules/archetypes/variables.tf
- This PR applies an update to fix issue #241
1. Update condition on validation for `scope_id` input variable in the archetype child module - fixes #241 
2. Update condition on validation for `root_id` input variable in the archetype child module for consistency and to provide better support for broader Management Group naming standards
None
> Update validation to fix #241

- docs/wiki/[User-Guide]-Module-Variables.md
- docs/wiki/[Variables]-template_file_variables.md
- modules/archetypes/variables.tf
- variables.tf
This PR updates the object type for the `template_file_variables` input variable to allow specifying a map of objects containing different object types.
This change is necessary due to the way `may(any)` expects the object to be a map with values of the same type.
1. Fixes #253, adding support for mixed object types in the `template_file_variables` input variable to enable full use of the `template()` function in Terraform
2. Updates Wiki documentation to reflect this change
None
This change is as per the narrative in #253 and all automated tests will be used as evidence that this
> Update to allow mixed types in object

- .github/workflows/wiki-sync.yml
Update wiki sync on release publish, not push to main.
Means we can update wiki source asyns whilst preparing for a release, without changing active documentation
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows?ref=hackernoon.com#release
> Wiki sync - update on release publish

- README.md
- docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Connectivity-Resources.md
- docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
- docs/wiki/[Examples]-Deploy-Default-Configuration.md
- docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
- docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Identity-Resources.md
- docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Management-Resources.md
- docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
- docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
- docs/wiki/[Examples]-Override-Module-Role-Assignments.md
- docs/wiki/[User-Guide]-Getting-Started.md
- docs/wiki/[User-Guide]-Provider-Configuration.md
- locals.tf
- modules/archetypes/locals.archetype_definitions.tf
- tests/deployment/planned_values.json
Hotfix to resolve YAML decode issue for `archetype extensions` and `archetype exclusions`.
1. Fix #278
none
Requesting customer to test.
> Fix YAML for `archetype extensions` and `archetype exclusions`

- .gitattributes
- .gitconfig
- .github/scripts/EnterpriseScaleLibraryTools/EnterpriseScaleLibraryTools.psm1
- .github/scripts/Invoke-LibraryUpdate.ps1
Previously, files would be created with `CRLF` line endings when running the `Invoke-LibraryUpdate` script on Windows.
This PR adds a new `Edit-LineEndings` function to simplify local running of the `Invoke-LibraryUpdate.ps1` script on different OS versions to ensure the original `LF` line endings are used.
This prevents Git from incorrectly tracking changes to files which have had the line endings incorrectly updated.
> The default is line ending type is set to `unix` (aka `LF`) on the assumption that git is configured to "check out as is". Users may need to change this value if git is configured differently.
1. Adds a new `Edit-LineEndings` function
2. Updates the `Export-LibraryArtifact` function to use `Edit-LineEndings`
3. Updates the `Invoke-LibraryUpdate` script to use …
> Add `Edit-LineEndings` to simplify local running

- .github/fabricbot.json
Adds the `fabricbot.json` config file from the FabricBot config portal to the correct location of `.github/`
1. Fixes #293 
**None**
This has been done in the ALZ-Bicep repo successfully. https://github.com/Azure/ALZ-Bicep/blob/main/.github/fabricbot.json
> Add FabricBot Config-as-Code 

- modules/archetypes/lib/archetype_definitions/archetype_definition_es_corp.tmpl.json
- modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_databricks_public_ip.tmpl.json
- modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_databricks_sku.tmpl.json
- modules/archetypes/lib/policy_assignments/policy_assignment_es_deny_databricks_vnet.tmpl.json
Add Missing Databricks Default Policy Assignments to Corp MG to Match ALZ Accelerator Experience 
1. Add 3 policy assignments for databricks to `corp` Management Groupto match ALZ Accelerator experience 
- Deny-DataB-Pip
- Deny-DataB-Sku
- Deny-DataB-Vnet
2. Fixes #295 
None
Automated testing will suffice
> Add Missing Databricks Default Policy Assignments to Corp MG to Match ALZ Accelerator Experience 

- locals.telemetry.connectivity.tf
- locals.telemetry.core.tf
- locals.telemetry.identity.tf
- locals.telemetry.management.tf
- locals.telemetry.tf
- locals.tf
When setting `disable_telemetry = true`, we observe the following error:
```shell
╷
│ Error: Invalid index
│
│   on ..\..\..\locals.telemetry.connectivity.tf line 42, in locals:
│   42:       random_id.telem[0].hex
│     ├────────────────
│     │ random_id.telem is empty tuple
│
│ The given key does not identify an element in this collection value: the collection has no elements.
╵
```
This PR implements a fix to catch this error, allowing `disable_telemetry = true` to continue controlling the `random_id.telem` resource creation as desired.
1. Fixes the error above
2. Replaces instances of `var.` with `local.` for consistency
n/a
Snippet of errors before the fix:
Snippet of plan when `disable_telemetry = false`:
Snippet of plan when `disable_telemetry = true`:
> Fix `random_id.telem is empty tuple` error when `disable_telemetry = true`

- README.md
1. Fix README link to telemetry
- [] Updated the ["What's New?"](https://github.com/Azure/Enterprise-Scale/wiki/Whats-new) wiki page (located in the [Enterprise-Scale repo](https://github.com/Azure/Enterprise-Scale) in the directory: `/docs/wiki/whats-new.md`)
> Fix broken README.md link

- tests/modules/test_002_add_custom_core/baseline_values.json
- tests/modules/test_003_add_mgmt_conn/baseline_values.json
- tests/modules/test_lib/archetype_exclusions/archetype_exclusion_es_landing_zones.json
- tests/modules/test_lib/archetype_exclusions/archetype_exclusion_es_root.json
This PR adds two archetype exclusions to the custom `lib` folder in our test framework to ensure test coverage for this scenario in light or #353 
1. Adds `tests/modules/test_lib/archetype_exclusions/archetype_exclusion_es_landing_zones.json` to exclude the `Deny-Subnet-Without-Nsg` Policy Assignment from the `landing_zones` Management Group scope
2. Adds `tests/modules/test_lib/archetype_exclusions/archetype_exclusion_es_root.json` to exclude the `Deploy-LX-Arc-Monitoring` Policy Assignment from the `root` Management Group scope
3. Updates the `baseline_values.json` files in our test framework
4. Closes #353
n/a
Please see evidence in the referenced issue #353 and using `git-diff` for the `baseline_values.json` files in this PR.
> Test archetype exclusions

- docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Connectivity-Resources.md
- docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
- docs/wiki/[Examples]-Deploy-Default-Configuration.md
- docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
- docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Identity-Resources.md
- docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Management-Resources.md
- docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
- docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
- docs/wiki/[Examples]-Override-Module-Role-Assignments.md
- docs/wiki/[User-Guide]-Getting-Started.md
- docs/wiki/[User-Guide]-Module-Variables.md
- docs/wiki/[User-Guide]-Provider-Configuration.md
- docs/wiki/[Variables]-configure_management_resources.md
Changes to the documentation due to the addition of new variables in the Azure Landing Zone module that were causing terraform to fail at apply stage. 
This was the error when following the deploy connectivity resources with custom settings article:
Resolved by adding advanced_vpn_settings as per default values in variables.tf of the module.
This was the error when following the deploy management resources with custom settings article:
Resolved by adding enabled_defender_for_containers with a value of true. 
1. Error for missing "advanced_vpn_settings" variable attribute after following the article for deploy connectivity resources with custom settings and running terraform apply.
2. Error for missing "enable_defender_for_containers" variable attribute after following the article for …
> Documentation fixes due to missing variable attributes

- modules/connectivity/locals.tf
Added ternary operator to set enable_bgp to null if VPN SKU is Basic, otherwise set to true false as per existing coalesce function
1. fixes #369 
**creation of basic sku vpngw**
**creation of vpngw1 sku vpngw**
> Add enable_bgp condition for Basic VPNGW SKU

- modules/connectivity/locals.tf
Adds advanced block support for custom vnet peering naming.
1. Fixes #397
2. Fixes #403 
n/a
```text
=== RUN   TestConnectivityAdvancedVnetPeeringNameNotSet
TestConnectivityAdvancedVnetPeeringNameNotSet 2022-06-15T00:18:12+01:00 /Users/matt/code/terraform-azurerm-caf-enterprise-scale/tests/terratest/connectivity/advancedVnetPeeringName/retry.go:91: terraform [init -upgrade=false]
TestConnectivityAdvancedVnetPeeringNameNotSet 2022-06-15T00:18:14+01:00 /Users/matt/code/terraform-azurerm-caf-enterprise-scale/tests/terratest/connectivity/advancedVnetPeeringName/retry.go:91: terraform [plan -input=false -lock=false -no-color -lock=false -out=./tfplan --parallelism=20]
TestConnectivityAdvancedVnetPeeringNameNotSet 2022-06-15T00:18:27+01:00 …
```
> Feature Request -  Custom Setting Support for vnet peerings

- modules/management/locals.tf
- resources.management.tf
1. Fixes #398 
```text
ARM_SUBSCRIPTION_ID="00000000-0000-0000-0000-000000000000" make TESTPREFIX='TestManagementAdvanced' terratest
==> Running Go test...
cd tests/terratest && go test $(go list ./... |grep -v 'vendor'|grep -v 'utils')  -run ^TestManagementAdvanced
ok  	github.com/Azure/terraform-azurerm-caf-enterprise-scale/tests/terratest/connectivity/advancedVnetPeeringName	0.190s [no tests to run]
ok  	github.com/Azure/terraform-azurerm-caf-enterprise-scale/tests/terratest/management/advancedAutomationAccountIdentity	10.888s
```
Note: `identity` block must be enclosed in a list `[ ... ]`
```terraform
module "alz" {
source  = "Azure/caf-enterprise-scale/azurerm"
version = "2.x.x"
advanced = { …
```
> Add option to add identity block to an Automation Account

- modules/connectivity/locals.tf
- tests/modules/test_003_add_mgmt_conn/baseline_values.json
This PR is in relation to [Issue 450](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/450).
The PR resolves an issue whereby if the VNG or AF config within **settings.connectivity.tf** were set to **enabled=false**, but the **address_prefix** was populated with a CIDR range, then the module would attempt to create this subnet. This would result in either a failed deployment, or a subnet that potentially was not required.
1. Fixes the condition or logic, that a subnet for a Virtual Network Gateway or Azure Firewall will only be created if these objects are to be deployed, i.e. **settings.connectivity.tf** has **enabled = true**.
1. N/A
Please provide any testing evidence to show that your Pull Request works/fixes as described and planned (include screenshots, if …
> Updates to resolve issue #450

- .github/workflows/code-review.yml
- .github/workflows/gh-ado-sync.yml
<h2 id=overviewsummary>Overview/Summary </h2>
<p>Add Workflow Restriction to GH/ADO Sync to only allow workflow to run on this repository only and not forks. </p>
<h2 id=thisprfixesaddschangesremoves>This PR fixes/adds/changes/removes </h2>
<ol>
<li>Add Workflow Restriction to GH/ADO Sync to only allow workflow to run on this repository only and not forks. </li>
</ol>
<h3 id=breakingchanges>Breaking Changes </h3>
<p>None </p>
<h2 id=testingevidence>Testing Evidence </h2>
<p>Linting will suffice </p>
<h2 id=aspartofthispullrequestihave>As part of this Pull Request I have </h2>
<ul>
<li>[x] Checked for duplicate <a href="https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pulls">Pull Requests</a> </li>
<li>[x] Associated it with relevant <a …
> Add Workflow Restriction to GH/ADO Sync

- .github/workflows/gh-ado-sync.yml
This PR reverts ADO sync to `v1.1.4` on a pinned version as 'main' appears to be not working currently:
```shell
Run a[1](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/actions/runs/3376326929/jobs/5603916329#step:3:1)1smiles/GitSync@main
JSON configuration file loaded.
Setting logLevel to info...
TypeError: Cannot read properties of undefined (reading 'startsWith')
at GitSync.run (/home/runner/work/_actions/a11smiles/GitSync/main/gitsync.js:28:3[7](https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/actions/runs/3376326929/jobs/5603916329#step:3:8))
at Object.<anonymous> (/home/runner/work/_actions/a11smiles/GitSync/main/index.js:4:6)
at Module._compile (node:internal/modules/cjs/loader:1101:14)
at Object.Module._extensions..js …
```
> Pin ADO sync to `v1.1.4`

- resources.connectivity.tf
Fixes https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/508
This fixes the issue when using the Connectivity resource  `hub_networks.virtual_network_gateway.advanced_vpn_settings.vpn_client_configuration` and providing a `revoke_certificate` it would pass validation but when applying the plan it would fail to find the value of the resources provided. 
1. Fixes interaction value for `revoke_certificate`
> Fixed revoke_certificate variable iterator

- README.md
- docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Connectivity-Resources.md
- docs/wiki/[Examples]-Deploy-Custom-Landing-Zone-Archetypes.md
- docs/wiki/[Examples]-Deploy-Default-Configuration.md
- docs/wiki/[Examples]-Deploy-Demo-Landing-Zone-Archetypes.md
- docs/wiki/[Examples]-Deploy-Identity-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Identity-Resources.md
- docs/wiki/[Examples]-Deploy-Management-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Management-Resources.md
- docs/wiki/[Examples]-Deploy-Using-Module-Nesting.md
- docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources.md
- docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
- docs/wiki/[Examples]-Override-Module-Role-Assignments.md
- docs/wiki/[User-Guide]-Getting-Started.md
- docs/wiki/[User-Guide]-Provider-Configuration.md
- modules/connectivity/locals.tf
- modules/role_assignments_for_policy/terraform.tf
- resources.connectivity.tf
- terraform.tf
- tests/README.md
- tests/modules/settings/settings.connectivity.tf
- tests/modules/test_001_baseline/terraform.tf
- tests/modules/test_002_add_custom_core/terraform.tf
- tests/modules/test_003_add_mgmt_conn/baseline_values.json
- tests/modules/test_003_add_mgmt_conn/terraform.tf
- tests/opa/policy/readme.md
- tests/scripts/azp-strategy.ps1
This PR updates the firewall configuration options to fix the issues below
1. Fix #513 
2. Fix #447 
> **NOTE:** This PR introduces the fix for #513 via the `advanced` block. We plan to move this as part of refactoring the module to support `optional()` types within the input variables.
1. Update to the required minimum provider version from `v3.18.0` to `v3.19.0` to allow inclusion of added `sql_redirect_allowed` attribute on the `azurerm_firewall_policy` resource type
Evidence for #447 provided within the test suite and visible within `baseline_values.json`
For #513, we have also added `sql_redirect_allowed` which is set using the same logic which is tried and tested. This has been added via the `advanced` block to show that this setting is taking effect, but we don't currently have a …
> Update firewall configuration options

- RELEASE.md
- modules/connectivity/locals.tf
This PR adds a missing `privatelink.kubernetesconfiguration.azure.com` namespace to the private DNS zones for Azure Arc.
1. Missed in the fix for #482
None
See unit tests
> Add Kubernetes namespace for Arc DNS

- README.md
Add a link to the v2.4.1 to v3.0.0 guide in the Upgrade Guides section.
Adds the link to the v2.4.1 to v3.0.0 upgrade guide to Upgrade Guides section on the main README page.
1. Adds a link to the v2.4.1 to v3.0.0 upgrade guide on the main README page, as was missing.
N/A
N/A
> Add link to Upgrade to v3.0.0 guide

- modules/archetypes/lib/policy_assignments/policy_assignment_es_deploy_asc_monitoring.tmpl.json
- tests/modules/test_001_baseline/baseline_values.json
- tests/modules/test_002_add_custom_core/baseline_values.json
- tests/modules/test_003_add_mgmt_conn/baseline_values.json
Cleanup of the Microsoft Cloud Security Benchmark initiative assignment parameters to align with all RIs. These parameters were set to disable a handful of policies in the initiative inconsistently across RIs and have now reverted to defaults.
Also updated assignment display name and description to align across RIs.
1. Removed parameters in the policy_assignment_es_deploy_asc_monitoring.tmpl.json to revert to initiative defaults.
2. Updated display name and description to correctly reflect the initiative assignment objectives.
3. Fixes #528
1. None
> Update MCSB policy assignment

- .github/workflows/update-policy.yml
This PR updates the `Update Library Templates` workflow to run on a daily schedule (weekdays only) at 08:00 to improve visibility of incoming policy changes from the upstream repository.
Will exclude updates to docs as this is an internal process.
1. _See description_
none
This change cannot be tested without merging to validate, but updated `cron` is based on previous entry and that used for Bicep implementation.
> Revert `Update Library Templates` workflow to use schedule

- RELEASE.md
- docs/wiki/[Variables]-configure_connectivity_resources.md
- docs/wiki/[Variables]-configure_connectivity_resources.settings.hub_networks.md
- docs/wiki/[Variables]-configure_connectivity_resources.settings.vwan_hub_networks.md
- modules/connectivity/locals.tf
- modules/connectivity/variables.tf
- variables.tf
This PR updates a number of default values for `optional()` connectivity inputs within the `configure_connectivity_resources` to allow `null` values to correctly pass-through as needed for optional resource attributes.
1. Fixes #556 
None
Please see outcome of `/azp run update` as this should show no changes from this PR.
> Update `optional()` defaults

- docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-orchestration.md
- docs/wiki/[Examples]-Deploy-using-multiple-module-declarations-with-remote-state.md
- examples/400-multi-with-orchestration/variables.tf
- examples/400-multi-with-remote-state/connectivity/variables.tf
This PR updates the recently added examples for deploying using multiple module declarations, to disable deployment of DDoS protection by default.
This change is to reduce the risk of bill-shock due to the high cost of this service.
n/a
n/a
n/a
> Disable DDoS protection by default

- .github/workflows/gh-ado-sync.yml
- RELEASE.md
- docs/wiki/[User-Guide]-Module-Variables.md
- docs/wiki/[Variables]-archetype_config_overrides.md
- variables.tf
This PR updates the `archetype_config_overrides` description to provide greater clarity around when to use this input.
1. Fix #573
none
No functional code changes.
> Update `archetype_config_overrides` description

- .github/workflows/gh-ado-sync.yml
This PR removes the concurrency logic from ADO sync workflow as it results in different issues to those faced without.
n/a
n/a
n/a
> Revert concurrency logic

- RELEASE.md
- docs/wiki/[User-Guide]-Archetype-Definitions.md
- locals.management_groups.tf
- locals.tf
- modules/archetypes/locals.policy_assignments.tf
- modules/archetypes/locals.tf
- tests/modules/settings/settings.core.tf
- tests/modules/test_002_add_custom_core/baseline_values.json
- tests/modules/test_003_add_mgmt_conn/baseline_values.json
- tests/modules/test_lib/policy_assignments/policy_assignment_test_policy_set_definition.json
This PR includes an update to the way parameters for policy assignments are merged when specified in different locations.
Currently, parameters are merged on a "per-policy" basis. This means that anyone wanting to specify custom values must ensure ALL required parameters are set for the target policy assignment. This can be challenging to get right, especially when amending policies with parameter managed dynamically by the module as discussed in #607.
This PR adds new logic which allows us to merge custom values on a "per-parameter" basis. This ensures that parameter values set at lower scopes are retained unless explicitly overwritten.
1. Fix #607
None. Customer who are already specifying custom parameter values will have had to specify all parameters at the target scope. This change …
> Update parameter merge logic

- locals.telemetry.connectivity.tf
- locals.telemetry.core.tf
This PR adds adds some new telemetry collection to the existing bitfield deployments so we can learn more about how the module is being used.
1. [AB#27173](https://dev.azure.com/CSUSolEng/2a9d5a5a-8998-4ad0-81c8-ef3045e4da97/_workitems/edit/27173) - Zero Trust Networking Phase 1 - https://github.com/Azure/Enterprise-Scale/wiki/Deploying-ALZ-CustomerUsage#alz-acceleratoreslz-arm-deployment---zero-trust-networking---phase-1--definition
2. Telemetry for Custom Library Enabled
None
Screenshot of deploying module with defaults and then adding connectivity config with AzFW Premium 
Can be seen on internal dashboards from test deployment
> Module Telemetry Enhancements/Additions - Custom Library & Zero Trust Networking Phase 1

- tests/pipelines/tests-e2e.yml
Timeouts of 1 hour insufficient to prevent job cancellation and state file locking
Increases to 2h
> ci: increase job timeout to prevent tf state locking

- modules/connectivity/locals.tf
- tests/modules/test_001_baseline/baseline_values.json
- tests/modules/test_002_add_custom_core/baseline_values.json
- tests/modules/test_003_add_mgmt_conn/baseline_values.json
Fixing bug that causes error when attempting to use custom naming for Public Ips when using the Azure Firewall Basic SKU. 
1. Adds complete customization for Azure Firewall Management PIP.
2. Fixes duplicate object key error.
No breaking changes.
Test settings: 
Terraform Plan: 
Azure Firewall Main PIP, 
Azure Firewall Management PIP,
> Bug: Duplicate Object Key Firewall PIP

- docs/wiki/[Examples]-Expand-built-in-archetype-definitions.md
This PR updates the examples in the documentation for policy assignment exclusions to include policy assignments that exist since the last major policy refresh.
1. #797 
None
N/A documentation only
> Docs: Fix documentation for recent policy updates

- docs/wiki/[Examples]-Deploy-policies-without-enforcing-them.md
The docs and example are being updated to reflect the true functionality and provide a working example. The previous docs were incorrect, presumably from a previous iteration of the functionality.
1. https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/803
N/A
N/A
> docs: fix policy enforcement override example

- examples/400-multi-with-orchestration/variables.tf
- locals.tf
- modules/connectivity/locals.geo_codes.tf.json
- modules/connectivity/locals.tf
- modules/management/locals.tf
- tests/modules/test_001_baseline/variables.tf
This PR adds Italy North as a supported region.
It also helps with case sensitivity in the locations for networking, to avoid errors related to the casing of the location supplied in variables.
1. #833 
None
E2E and Unit Tests have been run in this PR. The test input location casing has been updated such that they would have broken the tests prior to this update.
> Add Italy North and avoid casing issues

- resources.virtual_wan.tf
This PR addresses the issue described in the issue #868 - routing_intent does not find the next hop destination when deployed with the azurerm firewall in vhub.
no
Before the fix:
```
API Response:
│ 
│ ----[start]----
│ {"status":"Failed","error":{"code":"InvalidNextHop","message":"The next hop '/subscriptions/xxxxxx/resourceGroups/connectivity/providers/Microsoft.Network/azureFirewalls/fw-hub-japaneast' in route/policy 'routing-intent-policy-all' in the resource '/subscriptions/xxxxxx/resourceGroups/connectivity/providers/Microsoft.Network/virtualHubs/hub-japaneas …
```
> Fix routing intent deployment issue in virtual wan

- .github/workflows/update-policy.yml
This pull request includes a modification to the `.github/workflows/update-policy.yml` file. The change adds permissions for `contents` and `pull-requests` to the `update-templates` job, granting write access. This will allow the job to update library templates by writing to the repository's contents and creating or modifying pull requests.
> Fix GITHUB_TOKEN Permissions for Policy Sync Workflow due to recent Changes 

- modules/connectivity/locals.tf
Been an outstanding request for a while but finally got a chance to look at this properly. The additional capability will allow users to override a Virtual Hub Virtual Network Connection name. The logic is the same as what was added for hub/spoke peerings via https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/pull/401
1.  https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/633
Evidence from local run:
Virtual Network Resource IDs added to relevant arrays withing settings.connectivity.tf:
Without a custom setting we get a randomly generated connection name:
With the custom setting for the target virtual network resource id added to the settings.connectivity.tf:
The random name is overridden:
Portal Views following deployment:
Adding a custom setting to a …
> feat(connectivity): custom Settings for Virtual Hub connection names

- README.md
- docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources-With-Custom-Settings.md
- modules/connectivity/locals.tf
- modules/connectivity/variables.tf
- resources.virtual_wan.tf
- tests/modules/settings/settings.connectivity.tf
- variables.tf
Add option to set `allow_non_virtual_wan_traffic` value to `true` or `false` in express route gateway.
1. *Give the option to set `allow_non_virtual_wan_traffic` to true in azurerm_express_route_gateway resource*
None 
On the latest azurerm versions ( v3.48.0 and higher ) **azurerm_express_route_gateway** resource has the option to set this value to true. At the time of writing CAF module has no option available .
We saw this issue in our Dev environment during terraform plan :  the value was true so using a newer azurerm version the value goes to false, which is the default. 
```
~ resource "azurerm_express_route_gateway" "virtual_wan" {
~ allow_non_virtual_wan_traffic = true -> false
id                            = "/subscriptions/xxxxx-xxxx-xxxx-xxxxx-xxxxxxxxxx/resourceGroups/dev-conne …
```
> feat(connectivity): Add option to set allow_non_virtual_wan_traffic in express route gateway.

- docs/wiki/[Examples]-Deploy-Connectivity-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources-With-Custom-Settings.md
- docs/wiki/[Examples]-Deploy-Virtual-WAN-Resources.md
- docs/wiki/[Examples]-Deploy-ZT-Network.md
- docs/wiki/[User-Guide]-Module-upgrade-guidance.md
- docs/wiki/[User-Guide]-Upgrade-from-v1.1.4-to-v2.0.0.md
- docs/wiki/[User-Guide]-Upgrade-from-v5.1.0-to-v5.2.0.md
The `threat_intelligence_allowlist` data type was updated in 5.2.0 resulting in a breaking change for some users that was not properly identified.
- #922 
None
Docs only
> docs: update docs for threat_intelligence_allowlist

- modules/connectivity/locals.tf
- resources.virtual_wan.tf
This PR adds the hub_routing_preference option to the advanced configuration section of azurerm_virtual_hub. 
The default value is the same as for the azurerm provider ("ExpressRoute") so by default no changes will occur when upgrading.
There doesn't seem to be documentation for advanced configs that needs to be updated, let me know if I just missed it and I will update it.
This PR relates to issue https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/issues/861
See azurerm documentation for this option [here](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_hub#hub_routing_preference)
1. Adds hub_routing_preference option
In a local test I've modified the custom_settings_by_resource_type block of …
> Added hub_routing_preference to connectivity advanced configuration

- .gitignore
- examples/400-multi-with-orchestration/main.tf
- examples/400-multi-with-orchestration/modules/core/lib/policy_assignment_es_deploy_vmss_monitoring.tmpl.json.tftpl
- examples/400-multi-with-orchestration/template_file_variables.auto.tfvars
The UAMI for policy int he example code fails due to hard coded resource id. This fixes it by creating the UAMI as part of the example.
N/A
None, example only
> Fix example uami issue

- README.md
- _README_header.md
- docs/wiki/Frequently-Asked-Questions.md
Minor doc updates
1. Adds readme header to warn of upcoming changes with v7
2. FAQ on futures
> docs: update docs with FAQ on roadmap and banner for upcoming breaking changes

- resources.management_groups.tf
Fixes a regression in 6.0.0
1. #1024 
Tested in locally and it works.
> fix(management): azapi_resource.diag_settings

- modules/connectivity/locals.tf
The introduction of scm.privatelink.azurewebsites.net DNS zone breaks DNS resolution for the SCM endpoints.
Since by default it resolves via privatelink.azurewebsites.net already, there is no reason for the SCM zone to exist.
1. #1064
1.  It unbreaks this breaking change.
It's known to work, i don't want to break my env again just to prove it :)
> Removed SCM privatelink since it breaks DNS resolution

- main.tf
- modules/connectivity/README.md
- modules/connectivity/locals.tf
- modules/connectivity/variables.tf
Azure static web apps are currently spawned without a known pattern in Public DNS zones with different partition ids in their FQDN. We are now counting [1,2,3,4,5].azurestaticapps.net with a unknown rising number.
Private DNS Zones are used for private Endpoints correspondingly (privatelink.[1,2,3,4,5].azurestaticapps.net.) and as of the CAF principals need to be known before deploying the first resources.
There is no programmatic approach known to me.
Feel free to adjust to your needs.
Examples for module calls:
```
configure_connectivity_resources = {
...
advanced = {}
}
configure_connectivity_resources = {
...
advanced = {
custom_privatelink_azurestaticapps_partitionids = [4, 5]
}
}
```
1. Adds all currently existing private DNS zones per default, when 'azure_web_apps_static_sites' is …
> Add possibility to manually set privatelink partition ids for azure static apps

- README.md
- _README_header.md
- docs/wiki/[User-Guide]-Getting-Started.md
- docs/wiki/[User-Guide]-Upgrade-from-v5.2.1-to-v6.0.0.md
- examples/400-multi-with-orchestration/modules/core/main.tf
- resources.virtual_wan.tf
- terraform.tf
- tests/README.md
- tests/modules/test_001_baseline/terraform.tf
- tests/modules/test_002_add_custom_core/terraform.tf
- tests/modules/test_003_add_mgmt_conn/terraform.tf
- tests/scripts/azp-strategy.ps1
1. Fixes #1135 - Race condition results in InternalServerError when deploying in vhub a firewall, an express route gateway, vhub peering and routing intent
2. Fixes #1136 - Updating existing vnet dns_server with Azure firewall leads to azurerm_virtual_network error.
3. *Replace me*
none
```
module.alz_connectivity.azurerm_virtual_hub_routing_intent.virtual_wan["/subscriptions/000000/resourceGroups/rg-prod-network-vwan/providers/Microsoft.Network/virtualHubs/lz-cl-hub-southeastasia/lz-cl-routingintent-southeastasia"]: Still creating... [6m40s elapsed]
module.alz_connectivity.azurerm_virtual_hub_routing_intent.virtual_wan["/subscriptions/000000/resourceGroups/rg-prod-network-vwan/providers/Microsoft.Network/ …
```
> Fixes #1135 and #1136

- modules/management/locals.tf
setting `retention_in_days` worked OK, but setting `daily_quota_gb` did not. We configured the daily cap from the Azure Portal but this automation rolls it back to be disabled. This PR makes it so we can set a value for our environment, and it is not rolled back. 
```terraform
~ resource "azurerm_log_analytics_workspace" "management" {
~ daily_quota_gb                          = 64 -> -1
id                                      = "/subscriptions/96f9ca86-6842-4c2f-aada-2daafa1b0b9c/resourceGroups/redpanda-mgmt/providers/Microsoft.OperationalInsights/workspaces/redpanda-la"
name                                    = "redpanda-la"
tags                                    = {
"deployedBy"   = "terraform/azure/caf-enterprise-scale"
"redpanda-org" = "azure-governance"
}
}
```
> management/log-analytics: Allow users to set a daily GB cap

- .github/workflows/update-policy.yml
- tests/pipelines/templates/tests-backend.yml
- tests/pipelines/templates/tests-common.yml
- tests/pipelines/templates/tests-loop.yml
- tests/pipelines/templates/tests-strategy.yml
- tests/pipelines/tests-e2e.yml
- tests/pipelines/tests-unit.yml
- tests/scripts/azp-backend.sh
- tests/scripts/azp-strategy.ps1
- tests/scripts/tf-destroy.sh
- tests/scripts/tf-init.sh
- tests/scripts/tf-prepare.sh
See successful run
https://dev.azure.com/mscet/CAE-ALZ-Terraform/_build/results?buildId=9798&view=results
> ci: migrate to oidc

- .github/scripts/Invoke-LibraryUpdatePolicyAssignmentArchetypes.ps1
- .github/scripts/Invoke-LibraryUpdatePolicyDefinitions.ps1
- .github/workflows/update-policy.yml
- tests/pipelines/templates/tests-backend.yml
- tests/pipelines/templates/tests-common.yml
- tests/pipelines/templates/tests-loop.yml
- tests/pipelines/templates/tests-strategy.yml
Works!
https://github.com/Azure/terraform-azurerm-caf-enterprise-scale/actions/runs/15735398178
> fix: policy sync script

- README.md
- _README_header.md
- modules/archetypes/README.md
- modules/archetypes/_README_header.md
- modules/connectivity/README.md
- modules/connectivity/_README_header.md
- modules/identity/README.md
- modules/identity/_README_header.md
- modules/management/README.md
- modules/management/_README_header.md
- modules/role_assignments_for_policy/README.md
- modules/role_assignments_for_policy/_README_header.md
Adds deprecation notice to all modules
> docs: add deprecation notice for Terraform CAF Enterprise Scale module
